# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1206, 855)
        self.verticalLayout = QtWidgets.QVBoxLayout(MainWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.LeftLayout = QtWidgets.QVBoxLayout()
        self.LeftLayout.setSpacing(2)
        self.LeftLayout.setObjectName("LeftLayout")
        self.label_27 = QtWidgets.QLabel(MainWindow)
        self.label_27.setObjectName("label_27")
        self.LeftLayout.addWidget(self.label_27)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(MainWindow)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.editAddress = QtWidgets.QLineEdit(MainWindow)
        self.editAddress.setEnabled(True)
        self.editAddress.setMinimumSize(QtCore.QSize(150, 0))
        self.editAddress.setBaseSize(QtCore.QSize(22, 0))
        self.editAddress.setObjectName("editAddress")
        self.horizontalLayout.addWidget(self.editAddress)
        self.label_7 = QtWidgets.QLabel(MainWindow)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.editTelemetryAddress = QtWidgets.QLineEdit(MainWindow)
        self.editTelemetryAddress.setMinimumSize(QtCore.QSize(150, 0))
        self.editTelemetryAddress.setObjectName("editTelemetryAddress")
        self.horizontalLayout.addWidget(self.editTelemetryAddress)
        self.buttonInitialize = QtWidgets.QPushButton(MainWindow)
        self.buttonInitialize.setObjectName("buttonInitialize")
        self.horizontalLayout.addWidget(self.buttonInitialize)
        self.LeftLayout.addLayout(self.horizontalLayout)
        self.line_16 = QtWidgets.QFrame(MainWindow)
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.LeftLayout.addWidget(self.line_16)
        self.label_6 = QtWidgets.QLabel(MainWindow)
        self.label_6.setObjectName("label_6")
        self.LeftLayout.addWidget(self.label_6)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(6)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_2 = QtWidgets.QLabel(MainWindow)
        self.label_2.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_10.addWidget(self.label_2)
        self.editMsgID = QtWidgets.QLineEdit(MainWindow)
        self.editMsgID.setMinimumSize(QtCore.QSize(40, 0))
        self.editMsgID.setMaximumSize(QtCore.QSize(60, 16777215))
        self.editMsgID.setObjectName("editMsgID")
        self.horizontalLayout_10.addWidget(self.editMsgID)
        self.label_3 = QtWidgets.QLabel(MainWindow)
        self.label_3.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_10.addWidget(self.label_3)
        self.editCmdCode = QtWidgets.QLineEdit(MainWindow)
        self.editCmdCode.setMinimumSize(QtCore.QSize(20, 0))
        self.editCmdCode.setMaximumSize(QtCore.QSize(60, 16777215))
        self.editCmdCode.setObjectName("editCmdCode")
        self.horizontalLayout_10.addWidget(self.editCmdCode)
        self.label_17 = QtWidgets.QLabel(MainWindow)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_10.addWidget(self.label_17)
        self.editParameter = QtWidgets.QLineEdit(MainWindow)
        self.editParameter.setObjectName("editParameter")
        self.horizontalLayout_10.addWidget(self.editParameter)
        self.buttonClear = QtWidgets.QPushButton(MainWindow)
        self.buttonClear.setObjectName("buttonClear")
        self.horizontalLayout_10.addWidget(self.buttonClear)
        self.LeftLayout.addLayout(self.horizontalLayout_10)
        self.buttonSend = QtWidgets.QPushButton(MainWindow)
        self.buttonSend.setObjectName("buttonSend")
        self.LeftLayout.addWidget(self.buttonSend)
        self.line_12 = QtWidgets.QFrame(MainWindow)
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.LeftLayout.addWidget(self.line_12)
        self.label_8 = QtWidgets.QLabel(MainWindow)
        self.label_8.setObjectName("label_8")
        self.LeftLayout.addWidget(self.label_8)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_19 = QtWidgets.QLabel(MainWindow)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 1, 2, 1, 1)
        self.editLocalTime = QtWidgets.QLineEdit(MainWindow)
        self.editLocalTime.setMinimumSize(QtCore.QSize(160, 0))
        self.editLocalTime.setObjectName("editLocalTime")
        self.gridLayout_3.addWidget(self.editLocalTime, 0, 3, 1, 1)
        self.editMET = QtWidgets.QLineEdit(MainWindow)
        self.editMET.setMinimumSize(QtCore.QSize(160, 0))
        self.editMET.setObjectName("editMET")
        self.gridLayout_3.addWidget(self.editMET, 1, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(MainWindow)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        self.editMST = QtWidgets.QLineEdit(MainWindow)
        self.editMST.setMinimumSize(QtCore.QSize(160, 0))
        self.editMST.setObjectName("editMST")
        self.gridLayout_3.addWidget(self.editMST, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(MainWindow)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 0, 2, 1, 1)
        self.editUniversalTime = QtWidgets.QLineEdit(MainWindow)
        self.editUniversalTime.setMinimumSize(QtCore.QSize(160, 0))
        self.editUniversalTime.setObjectName("editUniversalTime")
        self.gridLayout_3.addWidget(self.editUniversalTime, 0, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(MainWindow)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 1, 0, 1, 1)
        self.LeftLayout.addLayout(self.gridLayout_3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.buttonConfigTime = QtWidgets.QPushButton(MainWindow)
        self.buttonConfigTime.setObjectName("buttonConfigTime")
        self.horizontalLayout_3.addWidget(self.buttonConfigTime)
        self.buttonSetMstAsCurrent = QtWidgets.QPushButton(MainWindow)
        self.buttonSetMstAsCurrent.setObjectName("buttonSetMstAsCurrent")
        self.horizontalLayout_3.addWidget(self.buttonSetMstAsCurrent)
        self.LeftLayout.addLayout(self.horizontalLayout_3)
        self.line_2 = QtWidgets.QFrame(MainWindow)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.LeftLayout.addWidget(self.line_2)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_20 = QtWidgets.QLabel(MainWindow)
        self.label_20.setObjectName("label_20")
        self.gridLayout_5.addWidget(self.label_20, 0, 0, 1, 1)
        self.label_33 = QtWidgets.QLabel(MainWindow)
        self.label_33.setObjectName("label_33")
        self.gridLayout_5.addWidget(self.label_33, 1, 0, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.editBandpassAngle = QtWidgets.QLineEdit(MainWindow)
        self.editBandpassAngle.setObjectName("editBandpassAngle")
        self.horizontalLayout_11.addWidget(self.editBandpassAngle)
        self.label_30 = QtWidgets.QLabel(MainWindow)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_11.addWidget(self.label_30)
        self.buttonBandpassRotate = QtWidgets.QPushButton(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBandpassRotate.sizePolicy().hasHeightForWidth())
        self.buttonBandpassRotate.setSizePolicy(sizePolicy)
        self.buttonBandpassRotate.setMaximumSize(QtCore.QSize(100, 16777215))
        self.buttonBandpassRotate.setObjectName("buttonBandpassRotate")
        self.horizontalLayout_11.addWidget(self.buttonBandpassRotate)
        self.buttonBandpassStop = QtWidgets.QPushButton(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBandpassStop.sizePolicy().hasHeightForWidth())
        self.buttonBandpassStop.setSizePolicy(sizePolicy)
        self.buttonBandpassStop.setMaximumSize(QtCore.QSize(100, 16777215))
        self.buttonBandpassStop.setObjectName("buttonBandpassStop")
        self.horizontalLayout_11.addWidget(self.buttonBandpassStop)
        self.buttonBandpassHome = QtWidgets.QPushButton(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBandpassHome.sizePolicy().hasHeightForWidth())
        self.buttonBandpassHome.setSizePolicy(sizePolicy)
        self.buttonBandpassHome.setMaximumSize(QtCore.QSize(100, 16777215))
        self.buttonBandpassHome.setObjectName("buttonBandpassHome")
        self.horizontalLayout_11.addWidget(self.buttonBandpassHome)
        self.gridLayout_5.addLayout(self.horizontalLayout_11, 0, 1, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_35 = QtWidgets.QLabel(MainWindow)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_4.addWidget(self.label_35, 0, QtCore.Qt.AlignRight)
        self.editBandpassVelocity = QtWidgets.QLineEdit(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editBandpassVelocity.sizePolicy().hasHeightForWidth())
        self.editBandpassVelocity.setSizePolicy(sizePolicy)
        self.editBandpassVelocity.setMinimumSize(QtCore.QSize(0, 0))
        self.editBandpassVelocity.setMaximumSize(QtCore.QSize(40, 16777215))
        self.editBandpassVelocity.setObjectName("editBandpassVelocity")
        self.horizontalLayout_4.addWidget(self.editBandpassVelocity)
        self.label_36 = QtWidgets.QLabel(MainWindow)
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_4.addWidget(self.label_36, 0, QtCore.Qt.AlignRight)
        self.editBandpassAcceleration = QtWidgets.QLineEdit(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editBandpassAcceleration.sizePolicy().hasHeightForWidth())
        self.editBandpassAcceleration.setSizePolicy(sizePolicy)
        self.editBandpassAcceleration.setMinimumSize(QtCore.QSize(0, 0))
        self.editBandpassAcceleration.setMaximumSize(QtCore.QSize(40, 16777215))
        self.editBandpassAcceleration.setObjectName("editBandpassAcceleration")
        self.horizontalLayout_4.addWidget(self.editBandpassAcceleration)
        self.buttonBandpassConfig = QtWidgets.QPushButton(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBandpassConfig.sizePolicy().hasHeightForWidth())
        self.buttonBandpassConfig.setSizePolicy(sizePolicy)
        self.buttonBandpassConfig.setMaximumSize(QtCore.QSize(100, 16777215))
        self.buttonBandpassConfig.setObjectName("buttonBandpassConfig")
        self.horizontalLayout_4.addWidget(self.buttonBandpassConfig)
        self.gridLayout_5.addLayout(self.horizontalLayout_4, 1, 1, 1, 1)
        self.LeftLayout.addLayout(self.gridLayout_5)
        self.groupBox = QtWidgets.QGroupBox(MainWindow)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.radioBandpass1 = QtWidgets.QRadioButton(self.groupBox)
        self.radioBandpass1.setObjectName("radioBandpass1")
        self.horizontalLayout_19.addWidget(self.radioBandpass1)
        self.radioBandpass2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioBandpass2.setObjectName("radioBandpass2")
        self.horizontalLayout_19.addWidget(self.radioBandpass2)
        self.radioBandpass3 = QtWidgets.QRadioButton(self.groupBox)
        self.radioBandpass3.setObjectName("radioBandpass3")
        self.horizontalLayout_19.addWidget(self.radioBandpass3)
        self.radioBandpass4 = QtWidgets.QRadioButton(self.groupBox)
        self.radioBandpass4.setObjectName("radioBandpass4")
        self.horizontalLayout_19.addWidget(self.radioBandpass4)
        self.LeftLayout.addWidget(self.groupBox)
        self.line_5 = QtWidgets.QFrame(MainWindow)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.LeftLayout.addWidget(self.line_5)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.editPolarizerAngle = QtWidgets.QLineEdit(MainWindow)
        self.editPolarizerAngle.setToolTip("")
        self.editPolarizerAngle.setObjectName("editPolarizerAngle")
        self.horizontalLayout_12.addWidget(self.editPolarizerAngle)
        self.label_31 = QtWidgets.QLabel(MainWindow)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_12.addWidget(self.label_31)
        self.buttonPolarizerRotate = QtWidgets.QPushButton(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonPolarizerRotate.sizePolicy().hasHeightForWidth())
        self.buttonPolarizerRotate.setSizePolicy(sizePolicy)
        self.buttonPolarizerRotate.setMaximumSize(QtCore.QSize(100, 16777215))
        self.buttonPolarizerRotate.setObjectName("buttonPolarizerRotate")
        self.horizontalLayout_12.addWidget(self.buttonPolarizerRotate)
        self.buttonPolarizerStop = QtWidgets.QPushButton(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonPolarizerStop.sizePolicy().hasHeightForWidth())
        self.buttonPolarizerStop.setSizePolicy(sizePolicy)
        self.buttonPolarizerStop.setMaximumSize(QtCore.QSize(100, 16777215))
        self.buttonPolarizerStop.setObjectName("buttonPolarizerStop")
        self.horizontalLayout_12.addWidget(self.buttonPolarizerStop)
        self.buttonPolarizerHome = QtWidgets.QPushButton(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonPolarizerHome.sizePolicy().hasHeightForWidth())
        self.buttonPolarizerHome.setSizePolicy(sizePolicy)
        self.buttonPolarizerHome.setMaximumSize(QtCore.QSize(100, 16777215))
        self.buttonPolarizerHome.setObjectName("buttonPolarizerHome")
        self.horizontalLayout_12.addWidget(self.buttonPolarizerHome)
        self.gridLayout_6.addLayout(self.horizontalLayout_12, 0, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(MainWindow)
        self.label_22.setObjectName("label_22")
        self.gridLayout_6.addWidget(self.label_22, 0, 0, 1, 1)
        self.label_34 = QtWidgets.QLabel(MainWindow)
        self.label_34.setObjectName("label_34")
        self.gridLayout_6.addWidget(self.label_34, 1, 0, 1, 1)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_43 = QtWidgets.QLabel(MainWindow)
        self.label_43.setObjectName("label_43")
        self.horizontalLayout_15.addWidget(self.label_43, 0, QtCore.Qt.AlignRight)
        self.editPolarizerVelocity = QtWidgets.QLineEdit(MainWindow)
        self.editPolarizerVelocity.setMaximumSize(QtCore.QSize(40, 16777215))
        self.editPolarizerVelocity.setObjectName("editPolarizerVelocity")
        self.horizontalLayout_15.addWidget(self.editPolarizerVelocity)
        self.label_42 = QtWidgets.QLabel(MainWindow)
        self.label_42.setObjectName("label_42")
        self.horizontalLayout_15.addWidget(self.label_42, 0, QtCore.Qt.AlignRight)
        self.editPolarizerAcceleration = QtWidgets.QLineEdit(MainWindow)
        self.editPolarizerAcceleration.setMaximumSize(QtCore.QSize(40, 16777215))
        self.editPolarizerAcceleration.setObjectName("editPolarizerAcceleration")
        self.horizontalLayout_15.addWidget(self.editPolarizerAcceleration)
        self.buttonPolarizerConfig = QtWidgets.QPushButton(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonPolarizerConfig.sizePolicy().hasHeightForWidth())
        self.buttonPolarizerConfig.setSizePolicy(sizePolicy)
        self.buttonPolarizerConfig.setMaximumSize(QtCore.QSize(100, 16777215))
        self.buttonPolarizerConfig.setObjectName("buttonPolarizerConfig")
        self.horizontalLayout_15.addWidget(self.buttonPolarizerConfig)
        self.gridLayout_6.addLayout(self.horizontalLayout_15, 1, 1, 1, 1)
        self.LeftLayout.addLayout(self.gridLayout_6)
        self.groupBox_2 = QtWidgets.QGroupBox(MainWindow)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.radioPolarizer1 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioPolarizer1.setObjectName("radioPolarizer1")
        self.horizontalLayout_6.addWidget(self.radioPolarizer1)
        self.radioPolarizer2 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioPolarizer2.setObjectName("radioPolarizer2")
        self.horizontalLayout_6.addWidget(self.radioPolarizer2)
        self.radioPolarizer3 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioPolarizer3.setObjectName("radioPolarizer3")
        self.horizontalLayout_6.addWidget(self.radioPolarizer3)
        self.radioPolarizer4 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioPolarizer4.setObjectName("radioPolarizer4")
        self.horizontalLayout_6.addWidget(self.radioPolarizer4)
        self.radioPolarizer5 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioPolarizer5.setObjectName("radioPolarizer5")
        self.horizontalLayout_6.addWidget(self.radioPolarizer5)
        self.radioPolarizer6 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioPolarizer6.setObjectName("radioPolarizer6")
        self.horizontalLayout_6.addWidget(self.radioPolarizer6)
        self.LeftLayout.addWidget(self.groupBox_2)
        self.line_11 = QtWidgets.QFrame(MainWindow)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.LeftLayout.addWidget(self.line_11)
        self.label_13 = QtWidgets.QLabel(MainWindow)
        self.label_13.setObjectName("label_13")
        self.LeftLayout.addWidget(self.label_13)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_16 = QtWidgets.QLabel(MainWindow)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_9.addWidget(self.label_16)
        self.editObservationNum = QtWidgets.QLineEdit(MainWindow)
        self.editObservationNum.setMaximumSize(QtCore.QSize(50, 16777215))
        self.editObservationNum.setObjectName("editObservationNum")
        self.horizontalLayout_9.addWidget(self.editObservationNum)
        self.label_21 = QtWidgets.QLabel(MainWindow)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_9.addWidget(self.label_21)
        self.editRepeatNum = QtWidgets.QLineEdit(MainWindow)
        self.editRepeatNum.setMaximumSize(QtCore.QSize(50, 16777215))
        self.editRepeatNum.setObjectName("editRepeatNum")
        self.horizontalLayout_9.addWidget(self.editRepeatNum)
        self.label_24 = QtWidgets.QLabel(MainWindow)
        self.label_24.setText("")
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_9.addWidget(self.label_24)
        self.checkAE = QtWidgets.QCheckBox(MainWindow)
        self.checkAE.setObjectName("checkAE")
        self.horizontalLayout_9.addWidget(self.checkAE)
        self.spinAEAdjust = QtWidgets.QDoubleSpinBox(MainWindow)
        self.spinAEAdjust.setObjectName("spinAEAdjust")
        self.horizontalLayout_9.addWidget(self.spinAEAdjust)
        self.editExposureTime = QtWidgets.QLineEdit(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editExposureTime.sizePolicy().hasHeightForWidth())
        self.editExposureTime.setSizePolicy(sizePolicy)
        self.editExposureTime.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.editExposureTime.setObjectName("editExposureTime")
        self.horizontalLayout_9.addWidget(self.editExposureTime)
        self.label_25 = QtWidgets.QLabel(MainWindow)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_9.addWidget(self.label_25)
        self.buttonCapture = QtWidgets.QPushButton(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonCapture.sizePolicy().hasHeightForWidth())
        self.buttonCapture.setSizePolicy(sizePolicy)
        self.buttonCapture.setMinimumSize(QtCore.QSize(90, 0))
        self.buttonCapture.setMaximumSize(QtCore.QSize(100, 16777215))
        self.buttonCapture.setObjectName("buttonCapture")
        self.horizontalLayout_9.addWidget(self.buttonCapture)
        self.buttonCaptureStop = QtWidgets.QPushButton(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonCaptureStop.sizePolicy().hasHeightForWidth())
        self.buttonCaptureStop.setSizePolicy(sizePolicy)
        self.buttonCaptureStop.setMinimumSize(QtCore.QSize(90, 0))
        self.buttonCaptureStop.setMaximumSize(QtCore.QSize(100, 16777215))
        self.buttonCaptureStop.setObjectName("buttonCaptureStop")
        self.horizontalLayout_9.addWidget(self.buttonCaptureStop)
        self.LeftLayout.addLayout(self.horizontalLayout_9)
        self.line = QtWidgets.QFrame(MainWindow)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.LeftLayout.addWidget(self.line)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_15 = QtWidgets.QLabel(MainWindow)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_14.addWidget(self.label_15)
        self.editCameraOffsetX = QtWidgets.QLineEdit(MainWindow)
        self.editCameraOffsetX.setObjectName("editCameraOffsetX")
        self.horizontalLayout_14.addWidget(self.editCameraOffsetX)
        self.label_38 = QtWidgets.QLabel(MainWindow)
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_14.addWidget(self.label_38)
        self.editCameraOffsetY = QtWidgets.QLineEdit(MainWindow)
        self.editCameraOffsetY.setObjectName("editCameraOffsetY")
        self.horizontalLayout_14.addWidget(self.editCameraOffsetY)
        self.label_29 = QtWidgets.QLabel(MainWindow)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_14.addWidget(self.label_29)
        self.editCameraTemperature = QtWidgets.QLineEdit(MainWindow)
        self.editCameraTemperature.setMaximumSize(QtCore.QSize(60, 16777215))
        self.editCameraTemperature.setObjectName("editCameraTemperature")
        self.horizontalLayout_14.addWidget(self.editCameraTemperature)
        self.label_28 = QtWidgets.QLabel(MainWindow)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_14.addWidget(self.label_28)
        self.buttonConfigCamera = QtWidgets.QPushButton(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonConfigCamera.sizePolicy().hasHeightForWidth())
        self.buttonConfigCamera.setSizePolicy(sizePolicy)
        self.buttonConfigCamera.setObjectName("buttonConfigCamera")
        self.horizontalLayout_14.addWidget(self.buttonConfigCamera)
        self.LeftLayout.addLayout(self.horizontalLayout_14)
        self.label_14 = QtWidgets.QLabel(MainWindow)
        self.label_14.setObjectName("label_14")
        self.LeftLayout.addWidget(self.label_14)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_40 = QtWidgets.QLabel(MainWindow)
        self.label_40.setObjectName("label_40")
        self.horizontalLayout_17.addWidget(self.label_40)
        self.comboSequence = QtWidgets.QComboBox(MainWindow)
        self.comboSequence.setObjectName("comboSequence")
        self.horizontalLayout_17.addWidget(self.comboSequence)
        self.buttonSaveSequence = QtWidgets.QPushButton(MainWindow)
        self.buttonSaveSequence.setObjectName("buttonSaveSequence")
        self.horizontalLayout_17.addWidget(self.buttonSaveSequence)
        self.label_44 = QtWidgets.QLabel(MainWindow)
        self.label_44.setObjectName("label_44")
        self.horizontalLayout_17.addWidget(self.label_44)
        self.editSequenceId = QtWidgets.QLineEdit(MainWindow)
        self.editSequenceId.setObjectName("editSequenceId")
        self.horizontalLayout_17.addWidget(self.editSequenceId)
        self.label_41 = QtWidgets.QLabel(MainWindow)
        self.label_41.setObjectName("label_41")
        self.horizontalLayout_17.addWidget(self.label_41)
        self.editSequenceRepeat = QtWidgets.QLineEdit(MainWindow)
        self.editSequenceRepeat.setObjectName("editSequenceRepeat")
        self.horizontalLayout_17.addWidget(self.editSequenceRepeat)
        self.LeftLayout.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_11 = QtWidgets.QLabel(MainWindow)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_5.addWidget(self.label_11)
        self.editObsStart = QtWidgets.QLineEdit(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editObsStart.sizePolicy().hasHeightForWidth())
        self.editObsStart.setSizePolicy(sizePolicy)
        self.editObsStart.setMinimumSize(QtCore.QSize(100, 0))
        self.editObsStart.setObjectName("editObsStart")
        self.horizontalLayout_5.addWidget(self.editObsStart)
        self.label_12 = QtWidgets.QLabel(MainWindow)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_5.addWidget(self.label_12)
        self.editObsEnd = QtWidgets.QLineEdit(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editObsEnd.sizePolicy().hasHeightForWidth())
        self.editObsEnd.setSizePolicy(sizePolicy)
        self.editObsEnd.setMinimumSize(QtCore.QSize(100, 0))
        self.editObsEnd.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.editObsEnd.setObjectName("editObsEnd")
        self.horizontalLayout_5.addWidget(self.editObsEnd)
        self.checkObservationEnable = QtWidgets.QCheckBox(MainWindow)
        self.checkObservationEnable.setObjectName("checkObservationEnable")
        self.horizontalLayout_5.addWidget(self.checkObservationEnable)
        self.LeftLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.buttonObservationStart = QtWidgets.QPushButton(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonObservationStart.sizePolicy().hasHeightForWidth())
        self.buttonObservationStart.setSizePolicy(sizePolicy)
        self.buttonObservationStart.setObjectName("buttonObservationStart")
        self.horizontalLayout_8.addWidget(self.buttonObservationStart)
        self.buttonObservationStop = QtWidgets.QPushButton(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonObservationStop.sizePolicy().hasHeightForWidth())
        self.buttonObservationStop.setSizePolicy(sizePolicy)
        self.buttonObservationStop.setObjectName("buttonObservationStop")
        self.horizontalLayout_8.addWidget(self.buttonObservationStop)
        self.LeftLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_2.addLayout(self.LeftLayout)
        self.line_13 = QtWidgets.QFrame(MainWindow)
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.horizontalLayout_2.addWidget(self.line_13)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_32 = QtWidgets.QLabel(MainWindow)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_3.addWidget(self.label_32)
        self.buttonConnect = QtWidgets.QPushButton(MainWindow)
        self.buttonConnect.setObjectName("buttonConnect")
        self.verticalLayout_3.addWidget(self.buttonConnect)
        self.line_6 = QtWidgets.QFrame(MainWindow)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_3.addWidget(self.line_6)
        self.label_23 = QtWidgets.QLabel(MainWindow)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_3.addWidget(self.label_23)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.checkQuickView = QtWidgets.QCheckBox(MainWindow)
        self.checkQuickView.setChecked(True)
        self.checkQuickView.setObjectName("checkQuickView")
        self.horizontalLayout_7.addWidget(self.checkQuickView)
        self.checkDataSave = QtWidgets.QCheckBox(MainWindow)
        self.checkDataSave.setChecked(True)
        self.checkDataSave.setObjectName("checkDataSave")
        self.horizontalLayout_7.addWidget(self.checkDataSave)
        self.checkImageAnalysis = QtWidgets.QCheckBox(MainWindow)
        self.checkImageAnalysis.setChecked(True)
        self.checkImageAnalysis.setObjectName("checkImageAnalysis")
        self.horizontalLayout_7.addWidget(self.checkImageAnalysis)
        self.buttonConfigDAP = QtWidgets.QPushButton(MainWindow)
        self.buttonConfigDAP.setObjectName("buttonConfigDAP")
        self.horizontalLayout_7.addWidget(self.buttonConfigDAP)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.line_7 = QtWidgets.QFrame(MainWindow)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_3.addWidget(self.line_7)
        self.label_4 = QtWidgets.QLabel(MainWindow)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelImage = QtWidgets.QLabel(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelImage.sizePolicy().hasHeightForWidth())
        self.labelImage.setSizePolicy(sizePolicy)
        self.labelImage.setMinimumSize(QtCore.QSize(256, 256))
        self.labelImage.setText("")
        self.labelImage.setPixmap(QtGui.QPixmap("../../../../../.designer/backup/res/kasi_logo.png"))
        self.labelImage.setAlignment(QtCore.Qt.AlignCenter)
        self.labelImage.setObjectName("labelImage")
        self.verticalLayout_2.addWidget(self.labelImage)
        self.horizontalLayout_13.addLayout(self.verticalLayout_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.qvOutput = QtWidgets.QTextBrowser(MainWindow)
        self.qvOutput.setObjectName("qvOutput")
        self.verticalLayout_4.addWidget(self.qvOutput)
        self.horizontalLayout_13.addLayout(self.verticalLayout_4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.line_14 = QtWidgets.QFrame(MainWindow)
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.verticalLayout_3.addWidget(self.line_14)
        self.label_26 = QtWidgets.QLabel(MainWindow)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_3.addWidget(self.label_26)
        self.eventOutput = QtWidgets.QTextBrowser(MainWindow)
        self.eventOutput.setEnabled(True)
        self.eventOutput.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.eventOutput.setObjectName("eventOutput")
        self.verticalLayout_3.addWidget(self.eventOutput)
        self.line_15 = QtWidgets.QFrame(MainWindow)
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.verticalLayout_3.addWidget(self.line_15)
        self.label_10 = QtWidgets.QLabel(MainWindow)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_3.addWidget(self.label_10)
        self.hkOutput = QtWidgets.QTextBrowser(MainWindow)
        self.hkOutput.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.hkOutput.setObjectName("hkOutput")
        self.verticalLayout_3.addWidget(self.hkOutput)
        self.line_4 = QtWidgets.QFrame(MainWindow)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_3.addWidget(self.line_4)
        self.label_37 = QtWidgets.QLabel(MainWindow)
        self.label_37.setObjectName("label_37")
        self.verticalLayout_3.addWidget(self.label_37)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.buttonPerfStart = QtWidgets.QPushButton(MainWindow)
        self.buttonPerfStart.setObjectName("buttonPerfStart")
        self.horizontalLayout_18.addWidget(self.buttonPerfStart)
        self.buttonPerfStop = QtWidgets.QPushButton(MainWindow)
        self.buttonPerfStop.setObjectName("buttonPerfStop")
        self.horizontalLayout_18.addWidget(self.buttonPerfStop)
        self.label_39 = QtWidgets.QLabel(MainWindow)
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_18.addWidget(self.label_39)
        self.editPerfLogFile = QtWidgets.QLineEdit(MainWindow)
        self.editPerfLogFile.setObjectName("editPerfLogFile")
        self.horizontalLayout_18.addWidget(self.editPerfLogFile)
        self.verticalLayout_3.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.editParameter, self.buttonBandpassRotate)
        MainWindow.setTabOrder(self.buttonBandpassRotate, self.buttonBandpassStop)
        MainWindow.setTabOrder(self.buttonBandpassStop, self.buttonBandpassHome)
        MainWindow.setTabOrder(self.buttonBandpassHome, self.editPolarizerAngle)
        MainWindow.setTabOrder(self.editPolarizerAngle, self.buttonPolarizerRotate)
        MainWindow.setTabOrder(self.buttonPolarizerRotate, self.buttonPolarizerStop)
        MainWindow.setTabOrder(self.buttonPolarizerStop, self.buttonPolarizerHome)
        MainWindow.setTabOrder(self.buttonPolarizerHome, self.editExposureTime)
        MainWindow.setTabOrder(self.editExposureTime, self.buttonCapture)
        MainWindow.setTabOrder(self.buttonCapture, self.eventOutput)
        MainWindow.setTabOrder(self.eventOutput, self.hkOutput)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "GroundSystem"))
        self.label_27.setText(_translate("MainWindow", "Settings"))
        self.label.setText(_translate("MainWindow", "Host"))
        self.label_7.setText(_translate("MainWindow", "Client"))
        self.buttonInitialize.setText(_translate("MainWindow", "Initialize"))
        self.label_6.setText(_translate("MainWindow", "Command"))
        self.label_2.setText(_translate("MainWindow", "MsgID (Hex)"))
        self.label_3.setText(_translate("MainWindow", "CC (Dec)"))
        self.label_17.setText(_translate("MainWindow", "Parameter"))
        self.buttonClear.setText(_translate("MainWindow", "Clear"))
        self.buttonSend.setText(_translate("MainWindow", "Send"))
        self.label_8.setText(_translate("MainWindow", "Time"))
        self.label_19.setText(_translate("MainWindow", "Mission Elapsed Time"))
        self.label_5.setText(_translate("MainWindow", "Time (Local)"))
        self.label_9.setText(_translate("MainWindow", "Time (UTC)"))
        self.label_18.setText(_translate("MainWindow", "Mission Epoch Time"))
        self.buttonConfigTime.setText(_translate("MainWindow", "Config Time"))
        self.buttonSetMstAsCurrent.setText(_translate("MainWindow", "Set As Current Time"))
        self.label_20.setText(_translate("MainWindow", "Bandpass Control"))
        self.label_33.setText(_translate("MainWindow", "Settings"))
        self.label_30.setText(_translate("MainWindow", "deg"))
        self.buttonBandpassRotate.setText(_translate("MainWindow", "Rotate"))
        self.buttonBandpassStop.setText(_translate("MainWindow", "Stop"))
        self.buttonBandpassHome.setText(_translate("MainWindow", "Home"))
        self.label_35.setText(_translate("MainWindow", "Velocity (RPM)"))
        self.label_36.setText(_translate("MainWindow", "Acceleration (rev/sec^2)"))
        self.buttonBandpassConfig.setText(_translate("MainWindow", "Config"))
        self.groupBox.setTitle(_translate("MainWindow", "Bandpass Positions"))
        self.radioBandpass1.setText(_translate("MainWindow", "1"))
        self.radioBandpass2.setText(_translate("MainWindow", "2"))
        self.radioBandpass3.setText(_translate("MainWindow", "3"))
        self.radioBandpass4.setText(_translate("MainWindow", "4"))
        self.label_31.setText(_translate("MainWindow", "deg"))
        self.buttonPolarizerRotate.setText(_translate("MainWindow", "Rotate"))
        self.buttonPolarizerStop.setText(_translate("MainWindow", "Stop"))
        self.buttonPolarizerHome.setText(_translate("MainWindow", "Home"))
        self.label_22.setText(_translate("MainWindow", "Polarizer Control"))
        self.label_34.setText(_translate("MainWindow", "Settings"))
        self.label_43.setText(_translate("MainWindow", "Velocity (RPM)"))
        self.label_42.setText(_translate("MainWindow", "Acceleration (rev/sec^2)"))
        self.buttonPolarizerConfig.setText(_translate("MainWindow", "Config"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Polarization Angles"))
        self.radioPolarizer1.setText(_translate("MainWindow", "0"))
        self.radioPolarizer2.setText(_translate("MainWindow", "60"))
        self.radioPolarizer3.setText(_translate("MainWindow", "120"))
        self.radioPolarizer4.setText(_translate("MainWindow", "180"))
        self.radioPolarizer5.setText(_translate("MainWindow", "240"))
        self.radioPolarizer6.setText(_translate("MainWindow", "300"))
        self.label_13.setText(_translate("MainWindow", "Camera"))
        self.label_16.setText(_translate("MainWindow", "No"))
        self.label_21.setText(_translate("MainWindow", "Repeat"))
        self.checkAE.setText(_translate("MainWindow", "AE"))
        self.label_25.setText(_translate("MainWindow", "ms"))
        self.buttonCapture.setText(_translate("MainWindow", "Capture"))
        self.buttonCaptureStop.setText(_translate("MainWindow", "Stop"))
        self.label_15.setText(_translate("MainWindow", "x"))
        self.label_38.setText(_translate("MainWindow", "y"))
        self.label_29.setText(_translate("MainWindow", "Temperature"))
        self.label_28.setText(_translate("MainWindow", "degree"))
        self.buttonConfigCamera.setText(_translate("MainWindow", "Set"))
        self.label_14.setText(_translate("MainWindow", "Sequence"))
        self.label_40.setText(_translate("MainWindow", "Preset"))
        self.buttonSaveSequence.setText(_translate("MainWindow", "Save"))
        self.label_44.setText(_translate("MainWindow", "ID"))
        self.label_41.setText(_translate("MainWindow", "Repeat"))
        self.label_11.setText(_translate("MainWindow", "Start Time"))
        self.label_12.setText(_translate("MainWindow", "End Time"))
        self.checkObservationEnable.setText(_translate("MainWindow", "Enable"))
        self.buttonObservationStart.setText(_translate("MainWindow", "Start"))
        self.buttonObservationStop.setText(_translate("MainWindow", "Stop"))
        self.label_32.setText(_translate("MainWindow", "Telemetry"))
        self.buttonConnect.setText(_translate("MainWindow", "Connect"))
        self.label_23.setText(_translate("MainWindow", "Data Acquisition and Processing"))
        self.checkQuickView.setText(_translate("MainWindow", "QuickView"))
        self.checkDataSave.setText(_translate("MainWindow", "Save"))
        self.checkImageAnalysis.setText(_translate("MainWindow", "Image Analysis"))
        self.buttonConfigDAP.setText(_translate("MainWindow", "Config"))
        self.label_4.setText(_translate("MainWindow", "QuickView"))
        self.label_26.setText(_translate("MainWindow", "Event"))
        self.label_10.setText(_translate("MainWindow", "Status"))
        self.label_37.setText(_translate("MainWindow", "Performance Log"))
        self.buttonPerfStart.setText(_translate("MainWindow", "Start"))
        self.buttonPerfStop.setText(_translate("MainWindow", "Stop"))
        self.label_39.setText(_translate("MainWindow", "Log File"))

